<?php
// src/lang.php - Dictionary for English to Hindi translation

return [
    // Navigation & General
    'Overview' => 'अवलोकन',
    'Marketplace' => 'बाज़ार',
    'Deposit Funds' => 'पैसे जमा करें',
    'Withdraw' => 'निकासी',
    'My Investments' => 'मेरे निवेश',
    'Referrals' => 'रेफरल्स',
    'History' => 'इतिहास',
    'Settings' => 'सेटिंग्स',
    'Logout' => 'लॉग आउट',
    'Change Password' => 'पासवर्ड बदलें',
    'Cancel' => 'रद्द करें',
    'Save' => 'सहेजें',
    
    // Dashboard User
    'Welcome back,' => 'वापसी पर स्वागत है,',
    'Wallet Balance' => 'वॉलेट बैलेंस',
    'Active Investments' => 'सक्रिय निवेश',
    'Total Earnings' => 'कुल कमाई',
    'Quick Actions' => 'त्वरित कार्य',
    'Invest Now' => 'अभी निवेश करें',
    
    // Admin Sidebar
    'Admin Dashboard' => 'एडमिन डैशबोर्ड',
    'Products' => 'उत्पाद',
    'Manage Deposits' => 'जमा प्रबंधित करें',
    'Manage Withdrawals' => 'निकासी प्रबंधित करें',
    'Manage Users' => 'उपयोगकर्ता प्रबंधित करें',
    'Bonus Claims' => 'बोनस दावे',
    
    // Marketplace & Investments
    'Daily Reward' => 'दैनिक इनाम',
    'Duration' => 'अवधि',
    'days' => 'दिन',
    'Purchase Asset' => 'उत्पाद खरीदें',
    'Claim Daily Reward' => 'दैनिक इनाम का दावा करें',
    'Remaining' => 'शेष',
    'Exit Early' => 'जल्दी बाहर निकलें',
    'Confirm Purchase' => 'खरीद की पुष्टि करें',
    
    // Deposit & Withdraw
    'Deposit Amount' => 'जमा राशि',
    'Submit Deposit' => 'जमा जमा करें',
    'Withdraw Amount' => 'निकासी राशि',
    'Submit Request' => 'अनुरोध प्रस्तुत करें',
    'Status' => 'स्थिति',
    'Date' => 'तारीख',
    'Action' => 'कार्रवाई',
    'Pending' => 'लंबित',
    'Approved' => 'मंजूर',
    'Rejected' => 'अस्वीकृत',
    
    // Auth & Misc
    'Email' => 'ईमेल',
    'Password' => 'पासवर्ड',
    'Login' => 'लॉग इन करें',
    'Register' => 'रजिस्टर करें',
    'Processing...' => 'प्रक्रिया हो रही है...',
    
    // Tables
    'Name' => 'नाम',
    'Amount' => 'राशि',
    'User' => 'उपयोगकर्ता',
    'Actions' => 'कार्रवाइयां',
    'No records found.' => 'कोई रिकॉर्ड नहीं मिला।',
    
    // Layout & Headers
    'Dashboard' => 'डैशबोर्ड',
    'Operations' => 'संचालन',
    'Management' => 'प्रबंधन',
    'System Settings' => 'सिस्टम सेटिंग्स',
    'AeroPay' => 'एयरोपे',
    'AdminPay' => 'एडमिनपे',
    'Your premium wallet overview' => 'आपका प्रीमियम वॉलेट अवलोकन',
    'Lifetime statistics and workload metrics' => 'आजीवन आंकड़े और कार्यभार मेट्रिक्स',
    'Finance' => 'वित्त',
    'Utilities' => 'उपयोगिताएँ',
    
    // Admin Settings
    'System Configuration' => 'सिस्टम कॉन्फ़िगरेशन',
    'Configure receiving gateway codes, primary numbers and payout limits' => 'रिसीविंग गेटवे कोड, प्राथमिक नंबर और पेआउट सीमाएं कॉन्फ़िगर करें',
    'Receiving QR Code' => 'क्यूआर कोड प्राप्त कर रहा है',
    'Upload New QR Code Image' => 'नई क्यूआर कोड छवि अपलोड करें',
    'Upload QR Code' => 'क्यूआर कोड अपलोड करें',
    'Global Settings' => 'वैश्विक सेटिंग्स',
    'Primary UPI ID' => 'प्राथमिक यूपीआई आईडी',
    'Backup Global Video Ad URL' => 'बैकअप ग्लोबल वीडियो विज्ञापन यूआरएल',
    'Required Referrals Count (Withdrawals)' => 'आवश्यक रेफरल गणना (निकासी)',
    'Save Configuration' => 'कॉन्फ़िगरेशन सहेजें',
    'Active Deposit Tiers (Gold, Diamond, Platinum)' => 'सक्रिय जमा टियर (गोल्ड, डायमंड, प्लेटिनम)',
    'Tier' => 'टीयर',
    'UPI ID' => 'यूपीआई आईडी',
    'Save Tier' => 'टीयर सहेजें',
    'tier details saved successfully!' => 'टीयर विवरण सफलतापूर्वक सहेजा गया!',
    'Failed to load settings' => 'सेटिंग्स लोड करने में विफल',
    'QR code image uploaded.' => 'क्यूआर कोड छवि अपलोड की गई।',
    'System settings saved successfully!' => 'सिस्टम सेटिंग्स सफलतापूर्वक सहेजी गईं!',
    
    // Admin Dashboard
    'Dashboard' => 'डैशबोर्ड',
    'Lifetime statistics and pending transaction queues' => 'आजीवन आंकड़े और लंबित लेनदेन कतारें',
    'Pending Deposits' => 'लंबित जमा',
    'Manage Queue' => 'कतार प्रबंधित करें',
    'Pending Withdrawals' => 'लंबित निकासी',
    'Pending Bonus Claims' => 'लंबित बोनस दावे',
    'Total Approved Deposits' => 'कुल स्वीकृत जमा',
    'Total Completed Withdrawals' => 'कुल पूर्ण निकासी',
    'Failed to fetch statistics' => 'आंकड़े प्राप्त करने में विफल',
    
    // Admin Products
    'Yield Assets' => 'उपज संपत्ति',
    'Create and schedule video ad links for investment products' => 'निवेश उत्पादों के लिए वीडियो विज्ञापन लिंक बनाएं और शेड्यूल करें',
    'Create Product' => 'उत्पाद बनाएं',
    'No Yield Assets Yet' => 'अभी तक कोई उपज संपत्ति नहीं',
    'Create your first investment product to start earning.' => 'कमाई शुरू करने के लिए अपना पहला निवेश उत्पाद बनाएं।',
    'Create Yield Product' => 'यील्ड उत्पाद बनाएं',
    'Asset Name' => 'संपत्ति का नाम',
    'Purchase Price (in Rupees)' => 'खरीद मूल्य (रुपये में)',
    'Contract Duration (Days)' => 'अनुबंध अवधि (दिन)',
    'Daily Reward Percentage ROI (%)' => 'दैनिक इनाम प्रतिशत आरओआई (%)',
    'Daily Video Ad Watch Time (Seconds)' => 'दैनिक वीडियो विज्ञापन देखने का समय (सेकंड)',
    'Asset Photo/Banner Image' => 'संपत्ति फोटो/बैनर छवि',
    'Cancel' => 'रद्द करें',
    'Save Product' => 'उत्पाद सहेजें',
    'Configure Day-by-Day Ad Schedules' => 'दिन-प्रतिदिन के विज्ञापन शेड्यूल कॉन्फ़िगर करें',
    'Provide custom video links (.mp4 or Youtube) for each day of the contract. If empty, the backup global Daily Ad will be shown.' => 'अनुबंध के प्रत्येक दिन के लिए कस्टम वीडियो लिंक (.mp4 या Youtube) प्रदान करें। यदि खाली है, तो बैकअप ग्लोबल दैनिक विज्ञापन दिखाया जाएगा।',
    'Save Schedules' => 'शेड्यूल सहेजें',
    'Active' => 'सक्रिय',
    'Draft' => 'मसौदा',
    'Price' => 'मूल्य',
    'Duration' => 'अवधि',
    'Days' => 'दिन',
    'Schedule Ad Links' => 'विज्ञापन लिंक शेड्यूल करें',
    'Edit' => 'संपादित करें',
    'Delete' => 'हटाएं',
    'Edit Yield Product' => 'यील्ड उत्पाद संपादित करें',
    'Saving...' => 'सहेजा जा रहा है...',
    'Product updated successfully!' => 'उत्पाद सफलतापूर्वक अपडेट किया गया!',
    'Product created successfully!' => 'उत्पाद सफलतापूर्वक बनाया गया!',
    'Are you sure you want to delete' => 'क्या आप वाकई हटाना चाहते हैं',
    'Product deleted successfully.' => 'उत्पाद सफलतापूर्वक हटा दिया गया।',
    'Day' => 'दिन',
    'Failed to load ad link schedules' => 'विज्ञापन लिंक शेड्यूल लोड करने में विफल',
    'Product ad links schedule saved!' => 'उत्पाद विज्ञापन लिंक शेड्यूल सहेजा गया!',
    
    // Admin Deposits
    'Manage Deposits' => 'जमा प्रबंधित करें',
    'Approve or reject pending user deposit screenshots' => 'लंबित उपयोगकर्ता जमा स्क्रीनशॉट को स्वीकृत या अस्वीकार करें',
    'Request Queue' => 'अनुरोध कतार',
    'Select a deposit request to inspect proof and process' => 'प्रमाण और प्रक्रिया का निरीक्षण करने के लिए जमा अनुरोध का चयन करें',
    'No pending deposits found.' => 'कोई लंबित जमा नहीं मिला।',
    'User:' => 'उपयोगकर्ता:',
    'Select a request to review' => 'समीक्षा के लिए अनुरोध चुनें',
    'Failed to load deposits' => 'जमा लोड करने में विफल',
    'Request Audit' => 'अनुरोध ऑडिट',
    'Amount:' => 'राशि:',
    'Tx ID:' => 'लेन-देन आईडी:',
    'Not provided' => 'प्रदान नहीं किया गया',
    'Submitted:' => 'प्रस्तुत:',
    'Rejection Reason (if rejecting)' => 'अस्वीकृति कारण (यदि अस्वीकार कर रहे हैं)',
    'Incorrect Transaction ID, amount mismatched, etc.' => 'गलत लेन-देन आईडी, बेमेल राशि, आदि',
    'Reject Request' => 'अनुरोध अस्वीकार करें',
    'Approve Deposit' => 'जमा स्वीकृत करें',
    'Approving...' => 'स्वीकृत कर रहा है...',
    'Deposit approved and credited.' => 'जमा स्वीकृत और जमा किया गया।',
    'Failed to approve deposit' => 'जमा स्वीकृत करने में विफल',
    'Please enter a rejection reason' => 'कृपया अस्वीकृति कारण दर्ज करें',
    'Rejecting...' => 'अस्वीकार कर रहा है...',
    'Deposit request rejected.' => 'जमा अनुरोध अस्वीकृत कर दिया गया।',
    
    // Admin Withdrawals
    'Manage Withdrawals' => 'निकासी प्रबंधित करें',
    'Confirm payment transfers or reject cashout requests' => 'भुगतान हस्तांतरण की पुष्टि करें या कैशआउट अनुरोधों को अस्वीकार करें',
    'Select a withdrawal request to view bank details and process' => 'बैंक विवरण देखने और प्रक्रिया करने के लिए निकासी अनुरोध का चयन करें',
    'No pending withdrawals found.' => 'कोई लंबित निकासी नहीं मिली।',
    'Failed to load withdrawals' => 'निकासी लोड करने में विफल',
    'Preferred Type:' => 'पसंदीदा प्रकार:',
    'UPI ID' => 'यूपीआई आईडी',
    'UPI ID:' => 'यूपीआई आईडी:',
    'Bank Transfer' => 'बैंक ट्रांसफर',
    'Holder:' => 'धारक:',
    'Account No:' => 'खाता संख्या:',
    'IFSC:' => 'आईएफएससी:',
    'Cashout Details' => 'कैशआउट विवरण',
    'Requested Amount:' => 'अनुरोधित राशि:',
    'Requested At:' => 'पर अनुरोध किया गया:',
    'Incorrect account number, KYC mismatch, etc.' => 'गलत खाता संख्या, केवाईसी बेमेल, आदि',
    'Confirm Completed' => 'पूर्ण होने की पुष्टि करें',
    'Processing...' => 'प्रसंस्करण...',
    'Withdrawal marked as completed.' => 'निकासी पूर्ण के रूप में चिह्नित की गई।',
    'Withdrawal request rejected. Funds returned to user.' => 'निकासी अनुरोध अस्वीकृत। धनराशि उपयोगकर्ता को वापस कर दी गई।',
    
    // Admin Claims
    'Referral Claims' => 'रेफरल दावे',
    'Review and payout referral commissions milestone requests' => 'रेफरल कमीशन मील का पत्थर अनुरोधों की समीक्षा करें और भुगतान करें',
    'Pending Claims' => 'लंबित दावे',
    'Select a claim to review user roadmap milestone metrics and process' => 'उपयोगकर्ता रोडमैप मील का पत्थर मेट्रिक्स की समीक्षा और प्रक्रिया करने के लिए एक दावे का चयन करें',
    'No pending claims found.' => 'कोई लंबित दावा नहीं मिला।',
    'Claim:' => 'दावा:',
    'Failed to load claims' => 'दावे लोड करने में विफल',
    'Claim Verification' => 'दावा सत्यापन',
    'Claimant Account:' => 'दावेदार खाता:',
    'Milestone Bonus:' => 'मील का पत्थर बोनस:',
    'Earned from Friend:' => 'मित्र से अर्जित:',
    'Requested:' => 'अनुरोधित:',
    'KYC mismatch, inactive referred user, etc.' => 'केवाईसी बेमेल, निष्क्रिय संदर्भित उपयोगकर्ता, आदि',
    'Reject Claim' => 'दावा अस्वीकार करें',
    'Approve Payout' => 'भुगतान स्वीकृत करें',
    'Commission claim approved and credited.' => 'कमीशन दावा स्वीकृत और जमा किया गया।',
    'Claim rejected.' => 'दावा अस्वीकृत कर दिया गया।',
    
    // Admin Users
    'User Accounts' => 'उपयोगकर्ता खाते',
    'Search and audit active user ledgers or suspend/reactivate profiles' => 'सक्रिय उपयोगकर्ता खाता बही खोजें और ऑडिट करें या प्रोफाइल को निलंबित/पुनः सक्रिय करें',
    'Search by name, email, or mobile...' => 'नाम, ईमेल या मोबाइल द्वारा खोजें...',
    'Search' => 'खोज',
    'User' => 'उपयोगकर्ता',
    'Mobile' => 'मोबाइल',
    'Wallet Balance' => 'वॉलेट बैलेंस',
    'Status' => 'स्थिति',
    'Actions' => 'कार्रवाइयां',
    'Member Transactions' => 'सदस्य लेनदेन',
    'No user accounts found.' => 'कोई उपयोगकर्ता खाता नहीं मिला।',
    'Anonymous' => 'अनाम',
    'Anonymous User' => 'अनाम उपयोगकर्ता',
    'Audit' => 'ऑडिट',
    'Suspend' => 'निलंबित करें',
    'Activate' => 'सक्रिय करें',
    'Failed to load users' => 'उपयोगकर्ताओं को लोड करने में विफल',
    'User status toggled successfully.' => 'उपयोगकर्ता की स्थिति सफलतापूर्वक बदली गई।',
    'Failed to toggle user status' => 'उपयोगकर्ता की स्थिति बदलने में विफल',
    'Permanently delete account' => 'खाता स्थायी रूप से हटाएं',
    'and all historical requests? THIS ACTION IS IRREVERSIBLE.' => 'और सभी ऐतिहासिक अनुरोध? यह कार्रवाई अपरिवर्तनीय है।',
    'User deleted successfully.' => 'उपयोगकर्ता सफलतापूर्वक हटा दिया गया।',
    'Failed to delete user' => 'उपयोगकर्ता को हटाने में विफल',
    'Audit Log' => 'ऑडिट लॉग',
    'No transaction logs recorded.' => 'कोई लेनदेन लॉग दर्ज नहीं किया गया।',
    'Status:' => 'स्थिति:',
    'Failed to load transactions' => 'लेनदेन लोड करने में विफल',
    
    // User Dashboard
    'AeroPay - Overview' => 'एयरोपे - अवलोकन',
    'Your AeroPay balance and transaction highlights' => 'आपका एयरोपे बैलेंस और लेनदेन हाइलाइट्स',
    'AeroPay Card' => 'एयरोपे कार्ड',
    'Cardholder' => 'कार्डधारक',
    'Deposit' => 'जमा करें',
    'Withdraw' => 'निकासी',
    'Total Deposits' => 'कुल जमा',
    'Total Withdrawals' => 'कुल निकासी',
    'Recent Activity' => 'हाल की गतिविधि',
    'No transactions recorded.' => 'कोई लेनदेन दर्ज नहीं किया गया।',
    
    // User Marketplace
    'AeroPay - Marketplace' => 'एयरोपे - मार्केटप्लेस',
    'Invest in high-yield assets to secure daily rewards' => 'दैनिक पुरस्कार सुरक्षित करने के लिए उच्च-उपज वाली संपत्तियों में निवेश करें',
    'Confirm Purchase' => 'खरीद की पुष्टि करें',
    'Cancel' => 'रद्द करें',
    '% Daily ROI' => '% दैनिक आरओआई',
    'Duration:' => 'अवधि:',
    'Days | Watch Time:' => 'दिन | देखने का समय:',
    's' => 'सेकंड',
    'Purchase Price' => 'खरीद मूल्य',
    'Buy' => 'खरीदें',
    'Are you sure you want to purchase the asset "' => 'क्या आप वाकई संपत्ति "',
    '" for ' => '" को ',
    '?<br>Confirming will automatically debit this amount from your available balance.' => ' में खरीदना चाहते हैं?<br>पुष्टि करने पर यह राशि आपके उपलब्ध शेष से स्वतः कट जाएगी।',
    'Asset purchased successfully!' => 'संपत्ति सफलतापूर्वक खरीदी गई!',
    
    // User Investments
    'AeroPay - My Investments' => 'एयरोपे - मेरे निवेश',
    'Manage active yield contracts and watch daily ads to get your returns' => 'सक्रिय उपज अनुबंधों का प्रबंधन करें और अपना रिटर्न प्राप्त करने के लिए दैनिक विज्ञापन देखें',
    'Yield Earnings History' => 'उपज आय इतिहास',
    'Remaining' => 'शेष',
    'Claim Daily Reward' => 'दैनिक इनाम का दावा करें',
    'You do not have any active investment contracts. Buy yield assets from the Marketplace to get started.' => 'आपके पास कोई सक्रिय निवेश अनुबंध नहीं है। शुरू करने के लिए मार्केटप्लेस से उपज वाली संपत्तियां खरीदें।',
    '% ROI' => '% आरओआई',
    'Daily Yield:' => 'दैनिक उपज:',
    'Contract Expiry:' => 'अनुबंध समाप्ति:',
    ' Days remaining' => ' दिन शेष',
    'Completed' => 'पूर्ण',
    'Watch Ad' => 'विज्ञापन देखें',
    'Exit' => 'बाहर निकलें',
    'No logs found.' => 'कोई लॉग नहीं मिला।',
    'Purchased' => 'खरीदा गया',
    'Early Refund' => 'प्रारंभिक रिफंड',
    'Daily Ad Reward:' => 'दैनिक विज्ञापन इनाम:',
    'Are you sure you want to terminate "' => 'क्या आप वाकई "',
    '" contract early? Your initial purchase principal of ' => '" अनुबंध को जल्दी समाप्त करना चाहते हैं? आपकी ',
    ' will be immediately refunded to your wallet balance.' => ' की प्रारंभिक खरीद मूल राशि आपके वॉलेट बैलेंस में तुरंत वापस कर दी जाएगी।',
    'Contract exited. Balance refunded.' => 'अनुबंध से बाहर निकला गया। शेष राशि वापस कर दी गई।',
    'Daily ad watched completely! Click Claim Reward.' => 'दैनिक विज्ञापन पूरी तरह देखा गया! इनाम का दावा करें पर क्लिक करें।',
    'Reward credited to wallet!' => 'इनाम वॉलेट में जमा कर दिया गया!',
    
    // User Deposit
    'AeroPay – Deposit Funds' => 'एयरोपे - फंड जमा करें',
    'Add funds using UPI or direct Bank Transfer' => 'UPI या डायरेक्ट बैंक ट्रांसफर का उपयोग करके फंड जोड़ें',
    'Enter Deposit Amount' => 'जमा राशि दर्ज करें',
    'How much would you like to deposit?' => 'आप कितना जमा करना चाहेंगे?',
    'Amount (₹ Rupees)' => 'राशि (₹ रुपये)',
    'Minimum deposit: ₹1.00' => 'न्यूनतम जमा: ₹1.00',
    'Continue' => 'जारी रखें',
    'Send Payment' => 'भुगतान भेजें',
    'Scan QR code or transfer to the UPI ID below' => 'नीचे दिए गए QR कोड को स्कैन करें या UPI ID पर ट्रांसफर करें',
    'Deposit Amount' => 'जमा राशि',
    'No QR code available' => 'कोई QR कोड उपलब्ध नहीं है',
    'Loading...' => 'लोड हो रहा है...',
    'Back' => 'वापस',
    'I Have Paid' => 'मैंने भुगतान कर दिया है',
    'Upload Payment Proof' => 'भुगतान प्रमाण अपलोड करें',
    'Upload your payment receipt screenshot' => 'अपनी भुगतान रसीद का स्क्रीनशॉट अपलोड करें',
    'Payment Screenshot' => 'भुगतान स्क्रीनशॉट',
    'Click to upload screenshot' => 'स्क्रीनशॉट अपलोड करने के लिए क्लिक करें',
    'JPEG, PNG, WEBP — Max 5MB' => 'JPEG, PNG, WEBP - अधिकतम 5MB',
    'Transaction / Reference ID' => 'लेनदेन / संदर्भ आईडी',
    'Optional' => 'वैकल्पिक',
    'Submit Request' => 'अनुरोध सबमिट करें',
    'Error loading details' => 'विवरण लोड करने में त्रुटि',
    'Not configured' => 'कॉन्फ़िगर नहीं किया गया',
    'UPI ID copied to clipboard!' => 'UPI ID क्लिपबोर्ड पर कॉपी हो गया!',
    'Failed to copy UPI ID' => 'UPI ID कॉपी करने में विफल',
    'Please enter a valid deposit amount' => 'कृपया एक वैध जमा राशि दर्ज करें',
    'Minimum deposit amount is ₹1' => 'न्यूनतम जमा राशि ₹1 है',
    'Submitting...' => 'सबमिट कर रहा है...',
    'Deposit request submitted! Awaiting admin approval.' => 'जमा अनुरोध सबमिट कर दिया गया! व्यवस्थापक की स्वीकृति की प्रतीक्षा है।',
    'Failed to submit deposit request' => 'जमा अनुरोध सबमिट करने में विफल',
    
    // User Withdraw
    'AeroPay - Withdraw Funds' => 'एयरोपे - फंड निकालें',
    'Cash out your balance to bank or UPI' => 'अपने बैलेंस को बैंक या UPI में निकालें',
    'Available Balance:' => 'उपलब्ध शेष:',
    'Withdrawal Amount (Rupees)' => 'निकासी राशि (रुपये)',
    'Payment Type' => 'भुगतान का प्रकार',
    'Bank Account' => 'बैंक खाता',
    'UPI ID' => 'UPI ID',
    'Account Holder Name' => 'खाताधारक का नाम',
    'Account Number' => 'खाता संख्या',
    'IFSC Code' => 'IFSC कोड',
    'Swipe to confirm withdrawal' => 'निकासी की पुष्टि करने के लिए स्वाइप करें',
    'Swipe Right to Cashout' => 'कैशआउट करने के लिए दाईं ओर स्वाइप करें',
    'Requirement: You must invite %s friends with active deposits to unlock withdrawals. You currently have %s (%s remaining).' => 'आवश्यकता: निकासी को अनलॉक करने के लिए आपको सक्रिय जमा के साथ %s दोस्तों को आमंत्रित करना होगा। वर्तमान में आपके पास %s (%s शेष) हैं।',
    'Please enter a valid amount' => 'कृपया एक वैध राशि दर्ज करें',
    'UPI ID is required' => 'UPI ID आवश्यक है',
    'All bank account details are required' => 'बैंक खाते के सभी विवरण आवश्यक हैं',
    'Withdrawal request submitted successfully!' => 'निकासी अनुरोध सफलतापूर्वक सबमिट किया गया!',
    
    // User History
    'AeroPay - History' => 'एयरोपे - इतिहास',
    'Track deposits, withdrawals, yield earnings, and sales' => 'जमा, निकासी, उपज आय और बिक्री को ट्रैक करें',
    'Type Filter' => 'प्रकार फ़िल्टर',
    'All Transactions' => 'सभी लेनदेन',
    'Deposits' => 'जमा',
    'Withdrawals' => 'निकासी',
    'Asset Purchases' => 'संपत्ति खरीद',
    'Asset Sells' => 'संपत्ति बिक्री',
    'Daily Rewards' => 'दैनिक इनाम',
    'Start Date' => 'प्रारंभ तिथि',
    'End Date' => 'अंतिम तिथि',
    'Apply Filters' => 'फ़िल्टर लागू करें',
    'Previous' => 'पिछला',
    'Page 1 of 1' => 'पृष्ठ 1 का 1',
    'Next' => 'अगला',
    'Page' => 'पृष्ठ',
    'of' => 'का',
    'No matching transactions found.' => 'कोई मेल खाने वाला लेनदेन नहीं मिला।',
    'Purchase' => 'खरीद',
    'Reward:' => 'इनाम:',
    'Status:' => 'स्थिति:',
    'Reason:' => 'कारण:',
    
    // User Referrals
    'AeroPay - Referral Program' => 'एयरोपे - रेफ़रल प्रोग्राम',
    'Invite your friends to earn 5% cash rewards on their deposits' => 'अपने दोस्तों को उनके जमा पर 5% नकद पुरस्कार अर्जित करने के लिए आमंत्रित करें',
    'My Referral Code' => 'मेरा रेफ़रल कोड',
    'Copy' => 'कॉपी करें',
    'Claimable Commissions' => 'दावा करने योग्य कमीशन',
    'Claim All' => 'सभी का दावा करें',
    'Roadmap Progress' => 'रोडमैप प्रगति',
    'Referrals' => 'रेफ़रल',
    'Invited members with active deposits' => 'सक्रिय जमा के साथ आमंत्रित सदस्य',
    'Referred Members' => 'संदर्भित सदस्य',
    'Commissions Ledger' => 'कमीशन लेजर',
    'Commission Claims History' => 'कमीशन दावों का इतिहास',
    'Referral code copied to clipboard!' => 'रेफ़रल कोड क्लिपबोर्ड पर कॉपी हो गया!',
    'Failed to copy code' => 'कोड कॉपी करने में विफल',
    'No members referred.' => 'कोई सदस्य संदर्भित नहीं किया गया।',
    'Active Investor' => 'सक्रिय निवेशक',
    'Pending Deposit' => 'लंबित जमा',
    'Anonymous User' => 'अनाम उपयोगकर्ता',
    'No commissions pending.' => 'कोई कमीशन लंबित नहीं है।',
    'Bonus from' => 'से बोनस',
    'Deposit amount:' => 'जमा राशि:',
    'Claim' => 'दावा करें',
    'No claims logged.' => 'कोई दावा दर्ज नहीं किया गया है।',
    'Claim ID:' => 'दावा आईडी:',
    'Submitted:' => 'प्रस्तुत:',
    'Claim submitted! Awaiting admin approval.' => 'दावा प्रस्तुत किया गया! व्यवस्थापक की स्वीकृति की प्रतीक्षा है।',
    'Submitted %s claim requests!' => '%s दावा अनुरोध सबमिट किए गए!',
    
    // User Settings
    'AeroPay - Settings' => 'एयरोपे - सेटिंग्स',
    'Configure Profile details, KYC data, and password' => 'प्रोफ़ाइल विवरण, KYC डेटा और पासवर्ड कॉन्फ़िगर करें',
    'Profile' => 'प्रोफ़ाइल',
    'Payment Details' => 'भुगतान विवरण',
    'Profile Information' => 'प्रोफ़ाइल जानकारी',
    'Full Name' => 'पूरा नाम',
    'Mobile Number' => 'मोबाइल नंबर',
    'Date of Birth' => 'जन्म तिथि',
    'Aadhar Card Number (12 digits)' => 'आधार कार्ड नंबर (12 अंक)',
    'PAN Card Number (10 characters)' => 'पैन कार्ड नंबर (10 वर्ण)',
    'Save Profile' => 'प्रोफ़ाइल सहेजें',
    'Withdrawal Details' => 'निकासी विवरण',
    'Preferred Cashout Method' => 'पसंदीदा कैशआउट विधि',
    'Bank Transfer' => 'बैंक ट्रांसफर',
    'Saved UPI ID' => 'सहेजा गया UPI ID',
    'Saved Bank Details' => 'सहेजा गया बैंक विवरण',
    'Save Methods' => 'विधियाँ सहेजें',
    'Profile updated successfully!' => 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    'Payment configurations saved!' => 'भुगतान कॉन्फ़िगरेशन सहेजे गए!',
    
    // Layout Modals & Toasts
    'Current Password' => 'वर्तमान पासवर्ड',
    'Enter current password' => 'वर्तमान पासवर्ड दर्ज करें',
    'New Password' => 'नया पासवर्ड',
    'Enter new password' => 'नया पासवर्ड दर्ज करें',
    'Confirm New Password' => 'नए पासवर्ड की पुष्टि करें',
    'Re-enter new password' => 'नया पासवर्ड फिर से दर्ज करें',
    'Update Password' => 'पासवर्ड अपडेट करें',
    'Logging out...' => 'लॉग आउट हो रहा है...',
    'New passwords do not match' => 'नए पासवर्ड मेल नहीं खाते',
    'Updating...' => 'अपडेट हो रहा है...',
    'Password updated successfully!' => 'पासवर्ड सफलतापूर्वक अपडेट किया गया!',
    'Failed to update password' => 'पासवर्ड अपडेट करने में विफल'
];
